<?php

namespace Database\Seeders;

use App\Models\Puesto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PuestoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $list_puesto = [
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>11,'id_area'=>46,'nom_puesto'=>'GERENTE DE ADQUISICIÓN DE MATERIALES','id_nivel'=>2,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>8,'nom_puesto'=>'SECRETARIA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>8,'nom_puesto'=>'CAJERO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'ANALISTA PROGRAMADOR SR.','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>18,'nom_puesto'=>'GESTOR DE PROCESOS Y PROYECTOS','id_nivel'=>3,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'JEFE DE CONTABILIDAD Y LEGAL','id_nivel'=>3,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'ASISTENTE CONTABLE','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'AUXILIAR DE CONTABILIDAD','id_nivel'=>7,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>13,'id_area'=>19,'nom_puesto'=>'COORDINADOR DE CONTROL INTERNO','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>17,'nom_puesto'=>'ASISTENTE DE TESORERÍA','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'PRACTICANTE LEGAL','id_nivel'=>8,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>31,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE INFRAESTRUCTURA','id_nivel'=>3,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'TÉCNICO DE MANTENIMIENTO','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'AUXILIAR DE MANTENIMIENTO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'DISEÑADOR DE VISUAL MERCHANDISING','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'COORDINADOR SR. DE VISUAL MERCHANDISING','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'ASISTENTE DE VISUAL MERCHANDISING','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'ANALISTA JR. DE DISEÑO DE INTERIORES','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>34,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DEL TALENTO HUMANO','id_nivel'=>3,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>11,'nom_puesto'=>'COORDINADOR SR. DE RECURSOS HUMANOS','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>29,'nom_puesto'=>'COORD. DE CULTURA, CLIMA Y DESARROLLO','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>43,'nom_puesto'=>'ASISTENTE DE RECURSOS HUMANOS','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>32,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE SEGURIDAD Y SALUD','id_nivel'=>3,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>12,'nom_puesto'=>'AGENTE DE SEGURIDAD','id_nivel'=>9,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'OPERARIO DE LIMPIEZA','id_nivel'=>9,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>12,'nom_puesto'=>'COORDINADOR SR. DE SEGURIDAD','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>25,'nom_puesto'=>'COORDINADOR SR. DE SOPORTE TÉCNICO','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>13,'nom_puesto'=>'COORDINADOR JR. DE CAJA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'COORDINADOR JR. DE TIENDA','id_nivel'=>4,'id_sede_laboral'=>6,'perfil_infosap'=>'36','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE COORDINADOR DE TIENDA','id_nivel'=>7,'id_sede_laboral'=>6,'perfil_infosap'=>'36','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'CAJERO PRINCIPAL','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'5','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE CAJA','id_nivel'=>7,'id_sede_laboral'=>6,'perfil_infosap'=>'5','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'VENDEDOR','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'SURTIDOR VENDEDOR','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'ALMACENERO','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'14','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>44,'nom_puesto'=>'AGENTE DE SEGURIDAD','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'OPERARIO DE LIMPIEZA','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'JEFE DE TIENDAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>15,'id_area'=>37,'nom_puesto'=>'GERENTE DE OPERACIONES Y PLANEAMIENTO','id_nivel'=>2,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>5,'nom_puesto'=>'PLANNER COMERCIAL','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA DAMAS','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'ASISTENTE COMERCIAL','id_nivel'=>6,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>0,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA CABALLEROS','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>5,'nom_puesto'=>'PRACTICANTE COMERCIAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'COORDINADOR DE MARKETING','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'EJECUTIVO DE CUENTAS','id_nivel'=>5,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'LOCUTOR DE RADIO','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'GESTOR DE CONTENIDOS','id_nivel'=>7,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'CREADOR DE CONTENIDOS','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA NIÑOS Y ACCESORIOS','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'SUPERVISOR DE PICKING E INVENTARIO','id_nivel'=>4,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'SUPERVISOR DE COMPRAS E INGRESOS','id_nivel'=>4,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'SUPERVISOR DE DISTRIBUCIÓN','id_nivel'=>4,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'ALMACENERO','id_nivel'=>9,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'ASISTENTE DE INGRESOS','id_nivel'=>6,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'CHOFER DE REPARTO','id_nivel'=>9,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>12,'id_area'=>36,'nom_puesto'=>'GERENTE DE ADMINISTRACIÓN Y FINANZAS','id_nivel'=>2,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'JEFE DE UDP','id_nivel'=>3,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'COORDINADOR DE CONFECCIÓN','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'COORDINADOR DE ACABADOS','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'ENCARGADO DE CORTE Y TIZADO','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'AYUDANTE DE CORTE','id_nivel'=>7,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'ENCARGADO DE ALMACÉN DE TELAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'PATRONISTA','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'MUESTRISTA','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'INSPECTOR DE CONTROL DE ACABADOS','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'AUDITOR DE TALLERES EXTERNOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'AUDITOR DE INSPECCIÓN INTERNA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>1,'nom_puesto'=>'GERENTE GENERAL','id_nivel'=>2,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>1,'id_departamento'=>6,'id_area'=>38,'nom_puesto'=>'ASISTENTE DE GERENCIA','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>1,'nom_puesto'=>'AUXILIAR DE OFICINA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CORTADOR DE TELA','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>6,'nom_puesto'=>'AUXILIAR DE ALMACÉN E INVENTARIO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE DISTRIBUCIÓN','id_nivel'=>6,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'COORDINADOR SR. DE ALMACÉN Y SURTIDO','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>3,'nom_puesto'=>'ENCARGADO DE AVÍOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'ENCARGADO DE AVÍOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'PROGRAMADOR WEB','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'AUXILIAR DE CONTABILIDAD','id_nivel'=>8,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'ARQUITECTO SENIOR','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'ARQUITECTO','id_nivel'=>5,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>1,'nom_puesto'=>'asas','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'INSPECTOR DE CONTROL DE CORTE','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'COMMUNITY MANAGER JR.','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>11,'nom_puesto'=>'JEFE DE REMUNERACIONES Y RELACIONES LABORALES','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'TÉCNICO DE MANTENIMIENTO JR.','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CODIFICADOR','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>4,'id_departamento'=>13,'id_area'=>15,'nom_puesto'=>'COORDINADOR SR. DE CAJA','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'ASISTENTE E-COMMERCE','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'PROGRAMADOR EXTERNO','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>5,'nom_puesto'=>'COORDINADORA COMERCIAL CATEGORÍA PLUS SIZE','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'ASISTENTE DE REPROCESO Y EXTRACCIÓN','id_nivel'=>6,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>6,'nom_puesto'=>'AUXILIAR DE EXTRACCIÓN E INVENTARIO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>6,'nom_puesto'=>'AUXILIAR DE REPROCESO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE DESPACHO E E-COMMERCE','id_nivel'=>6,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>2,'nom_puesto'=>'JEFE DE DPTO. PLANEAMIENTO Y PRODUCCIÓN','id_nivel'=>3,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>5,'nom_puesto'=>'VENDEDOR E-COMMERCE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'ASISTENTE DE MARKETING','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>3,'nom_puesto'=>'asaf','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'AUXILIAR DE COSTURA','id_nivel'=>7,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'ASISTENTE DE LOGÍSTICA DE TELAS Y AVÍOS','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>13,'id_area'=>15,'nom_puesto'=>'COORDINADOR SR. DE CAJA','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'DESARROLLADOR DE FICHA TÉCNICA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'COORDINADOR DE CALIDAD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>40,'nom_puesto'=>'SUPERVISOR NACIONAL DE ABASTECIMIENTO E INVENTARIOS','id_nivel'=>4,'id_sede_laboral'=>5,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'OPERARIO DE COSTURA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>43,'nom_puesto'=>'PRACTICANTE DE RECURSOS HUMANOS','id_nivel'=>8,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>10,'nom_puesto'=>'AUXILIAR DE ARQUITECTURA','id_nivel'=>8,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>16,'nom_puesto'=>'COORDINADOR JR. DE VISUAL MERCHANDISING','id_nivel'=>4,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>27,'nom_puesto'=>'COORD. CALIDAD','id_nivel'=>4,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'JEFE DE MARKETING','id_nivel'=>3,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>17,'nom_puesto'=>'AUXILIAR DE TESORERÍA','id_nivel'=>7,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>10,'nom_puesto'=>'VISUAL MERCHANDISER','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'VISUAL MERCHANDISER','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'ASISTENTE DE TRENDING','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'PRACTICANTE DE DISEÑO','id_nivel'=>8,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'INSPECTOR DE CORTE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'DISEÑADORA DE MODAS','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>2,'nom_puesto'=>'ASISTENTE DE INGENIERÍA','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>11,'nom_puesto'=>'ASISTENTE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'OPERARIO DE CORTE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>25,'nom_puesto'=>'ASISTENTE DE SOPORTE TI','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE LOGÍSTICA DE TELAS','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>2,'nom_puesto'=>'SUPERVISOR DE ALMACÉN DE TELAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'EJECUTIVO COMERCIAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>40,'nom_puesto'=>'GESTOR DE STOCK ZONAL','id_nivel'=>7,'id_sede_laboral'=>5,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>5,'nom_puesto'=>'ASISTENTE DE PLANEAMIENTO COMERCIAL','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'DISEÑADOR GRÁFICO TEXTIL','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'SUPERVISOR DE MANTENIMIENTO','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>7,'nom_puesto'=>'ASISTENTE DE PROYECTOS','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>18,'nom_puesto'=>'AUXILIAR DE PROCESOS Y PROYECTOS','id_nivel'=>8,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>33,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE VENTAS','id_nivel'=>4,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'ASISTENTE DE UDP','id_nivel'=>6,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>21,'nom_puesto'=>'ANALISTA DE BUSINESS INTELLIGENCE','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'ADMINISTRADOR DE TIENDA','id_nivel'=>4,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'AUXILIAR DE UDP','id_nivel'=>7,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'AUXILIAR DE PICKING E INVENTARIO','id_nivel'=>7,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>21,'nom_puesto'=>'JEFE DE BUSINESS INTELLIGENCE','id_nivel'=>3,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>0,'nom_puesto'=>'ASISTENTE DE BUSINESS INTELLIGENCE','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE VISUAL MERCHANDISING','id_nivel'=>7,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'VENDEDOR CAJERO','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'5','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE VISUAL MERCHANDISING','id_nivel'=>7,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'AUXILIAR DE ALMACÉN DE AVÍOS','id_nivel'=>7,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CORTADOR JR. DE TELA','id_nivel'=>9,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>10,'id_area'=>2,'nom_puesto'=>'EXTERNO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 19','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>21,'nom_puesto'=>'ASISTENTE DE BUSINESS INTELLIGENCE','id_nivel'=>6,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'SUPERVISOR DE SERVICIOS (LIMPIEZA)','id_nivel'=>9,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 01','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 02','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 03','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 04','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 05','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 06','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 07','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 08','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 09','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>18,'nom_puesto'=>'BASE 10','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 11','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 12','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 13','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 15','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 16','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 17','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 18','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>2,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'BASE 14','id_nivel'=>9,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>10,'nom_puesto'=>'AUXILIAR DE ARQUITECTURA','id_nivel'=>7,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>18,'nom_puesto'=>'ANALISTA DE PROCESOS Y PROYECTOS','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'PRACTICANTE DE PCP /COORD. ACABADOS','id_nivel'=>8,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>0,'id_gerencia'=>4,'id_departamento'=>0,'id_area'=>14,'nom_puesto'=>'COORDINADOR SR. DE TIENDA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'COORDINADOR SR. DE TIENDA','id_nivel'=>4,'id_sede_laboral'=>6,'perfil_infosap'=>'36','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'ANALISTA DE FICHAS TÉCNICAS','id_nivel'=>5,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>11,'id_area'=>46,'nom_puesto'=>'ASISTENTE DE ADQUISICIÓN Y MARCAS','id_nivel'=>0,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>11,'id_area'=>46,'nom_puesto'=>'GERENTE DE ADQUISICIÓN DE MATERIALES','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>21,'nom_puesto'=>'ANALISTA DE BUSINESS INTELLIGENCE','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>21,'nom_puesto'=>'JEFE DE BUSINESS INTELLIGENCE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>13,'id_area'=>15,'nom_puesto'=>'COORDINADOR SR. DE CAJA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'ANALISTA DE PLANEAMIENTO COMERCIAL','id_nivel'=>0,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA CABALLEROS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA DAMAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'COORDINADOR COMERCIAL CATEGORÍA NIÑOS Y ACCESORIOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>5,'nom_puesto'=>'DISEÑADORA DE MODAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>26,'nom_puesto'=>'ASISTENTE DE COMPENSACIONES','id_nivel'=>6,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>26,'nom_puesto'=>'ASISTENTE SOCIAL','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'ALMACENERO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'ASISTENTE DE INGRESOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>6,'nom_puesto'=>'SUPERVISOR DE COMPRAS E INGRESOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'ASISTENTE CONTABLE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'AUXILIAR DE CONTABILIDAD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'JEFE DE CONTABILIDAD Y LEGAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>9,'nom_puesto'=>'PRACTICANTE LEGAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>27,'nom_puesto'=>'COORD. CALIDAD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>27,'nom_puesto'=>'INSP. CONTROL DE CALIDAD','id_nivel'=>0,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>13,'id_area'=>19,'nom_puesto'=>'COORDINADOR DE CONTROL INTERNO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'AYUDANTE DE CORTE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CODIFICADOR','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CORTADOR DE TELA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'CORTADOR JR. DE TELA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>28,'nom_puesto'=>'ENCARGADO DE CORTE Y TIZADO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>29,'nom_puesto'=>'ASISTENTE DE CULTURA, CLIMA Y DESARROLLO','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>29,'nom_puesto'=>'COORD. DE CULTURA, CLIMA Y DESARROLLO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'ANALISTA DE FICHAS TÉCNICAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'ASISTENTE DE UDP','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'AUXILIAR DE UDP','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'DISEÑADOR GRÁFICO TEXTIL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'MUESTRISTA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>47,'nom_puesto'=>'PATRONISTA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ALMACENERO','id_nivel'=>9,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE DESPACHO E E-COMMERCE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE DISTRIBUCIÓN','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'ASISTENTE DE LOGÍSTICA DE TELAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'AUXILIAR DE ALMACÉN DE AVÍOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'CHOFER DE REPARTO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'EXTERNO','id_nivel'=>0,'id_sede_laboral'=>3,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>30,'nom_puesto'=>'SUPERVISOR DE DISTRIBUCIÓN','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>31,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE INFRAESTRUCTURA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>32,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE SEGURIDAD Y SALUD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>33,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DE VENTAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>34,'nom_puesto'=>'JEFE DE DTO. GESTIÓN DEL TALENTO HUMANO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>35,'nom_puesto'=>'JEFE DE DTO. GESTIÓN LOGÍSTICA','id_nivel'=>0,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>12,'id_area'=>36,'nom_puesto'=>'GERENTE DE ADMINISTRACIÓN Y FINANZAS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>15,'id_area'=>37,'nom_puesto'=>'GERENTE DE OPERACIONES Y PLANEAMIENTO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>1,'id_departamento'=>6,'id_area'=>38,'nom_puesto'=>'ASISTENTE DE GERENCIA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>1,'id_departamento'=>6,'id_area'=>38,'nom_puesto'=>'DIRECTOR GENERAL','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>17,'id_area'=>39,'nom_puesto'=>'GERENTE DE GESTIÓN COMERCIAL','id_nivel'=>0,'id_sede_laboral'=>1,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>10,'nom_puesto'=>'AUXILIAR DE ARQUITECTURA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>40,'nom_puesto'=>'GESTOR DE STOCK ZONAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>40,'nom_puesto'=>'SUPERVISOR NACIONAL DE ABASTECIMIENTO E INVENTARIOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'EXTERNO','id_nivel'=>0,'id_sede_laboral'=>3,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'OPERARIO DE LIMPIEZA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'SUPERVISOR DE SERVICIOS (LIMPIEZA)','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'SUPERVISOR DE MANTENIMIENTO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>10,'id_area'=>41,'nom_puesto'=>'TÉCNICO DE MANTENIMIENTO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>2,'nom_puesto'=>'ASISTENTE DE INGENIERÍA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>2,'nom_puesto'=>'EXTERNO','id_nivel'=>0,'id_sede_laboral'=>3,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>2,'nom_puesto'=>'JEFE DE DPTO. PLANEAMIENTO Y PRODUCCIÓN','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'ASISTENTE COMERCIAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'ASISTENTE E-COMMERCE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'COORDINADOR DE MARKETING','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'CREADOR DE CONTENIDOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'DISEÑADOR DE VISUAL MERCHANDISING','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'GESTOR DE CONTENIDOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>3,'id_departamento'=>3,'id_area'=>7,'nom_puesto'=>'LOCUTOR DE RADIO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'ALMACENERO','id_nivel'=>9,'id_sede_laboral'=>2,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'ASISTENTE DE REPROCESO Y EXTRACCIÓN','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'AUXILIAR DE PICKING E INVENTARIO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>7,'id_area'=>42,'nom_puesto'=>'SUPERVISOR DE PICKING E INVENTARIO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>18,'nom_puesto'=>'ANALISTA DE PROCESOS Y PROYECTOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>18,'nom_puesto'=>'AUXILIAR DE PROCESOS Y PROYECTOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>18,'nom_puesto'=>'PRACTICANTE DE PROCESOS Y PROYECTOS','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>11,'nom_puesto'=>'ANALISTA DE RECLUTAMIENTO Y SELECCIÓN','id_nivel'=>0,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>11,'nom_puesto'=>'ASISTENTE DE RECLUTAMIENTO Y SELECCIÓN','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>43,'nom_puesto'=>'ANALISTA DE RECURSOS HUMANOS','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>43,'nom_puesto'=>'ASISTENTE DE RECURSOS HUMANOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>43,'nom_puesto'=>'PRACTICANTE DE RECURSOS HUMANOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>12,'nom_puesto'=>'AGENTE DE SEGURIDAD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>44,'nom_puesto'=>'AGENTE DE SEGURIDAD','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'COORDINADOR DE ACABADOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'COORDINADOR DE CONFECCIÓN','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'INSPECTOR DE CONTROL DE ACABADOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'INSPECTOR DE CONTROL DE CORTE','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>2,'id_gerencia'=>2,'id_departamento'=>4,'id_area'=>45,'nom_puesto'=>'PRACTICANTE DE PCP /COORD. ACABADOS','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'ANALISTA PROGRAMADOR SR.','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'PROGRAMADOR EXTERNO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>13,'nom_puesto'=>'PROGRAMADOR WEB','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>25,'nom_puesto'=>'ASISTENTE DE SOPORTE TI','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>25,'nom_puesto'=>'COORDINADOR SR. DE SOPORTE TÉCNICO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>17,'nom_puesto'=>'ASISTENTE DE TESORERÍA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>8,'id_area'=>17,'nom_puesto'=>'AUXILIAR DE TESORERÍA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'ADMINISTRADOR DE TIENDA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'ALMACENERO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE CAJA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE COORDINADOR DE TIENDA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'AUXILIAR DE VISUAL MERCHANDISING','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'CAJERO PRINCIPAL','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'COORDINADOR JR. DE TIENDA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'COORDINADOR SR. DE TIENDA','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'SURTIDOR VENDEDOR','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'VENDEDOR','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'VENDEDOR CAJERO','id_nivel'=>0,'id_sede_laboral'=>0,'perfil_infosap'=>'','estado'=>2],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>12,'nom_puesto'=>'SUPERVISOR DE SEGURIDAD - OFC','id_nivel'=>9,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>1,'id_area'=>44,'nom_puesto'=>'SUPERVISOR DE SEGURIDAD - TND','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>25,'nom_puesto'=>'PRACTICANTE DE SOPORTE TI','id_nivel'=>8,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>5,'id_area'=>26,'nom_puesto'=>'AUXILIAR DE BIENESTAR SOCIAL','id_nivel'=>7,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>2,'id_area'=>14,'nom_puesto'=>'BASE','id_nivel'=>9,'id_sede_laboral'=>6,'perfil_infosap'=>'','estado'=>1],
            ['id_direccion'=>1,'id_gerencia'=>4,'id_departamento'=>9,'id_area'=>21,'nom_puesto'=>'ANALISTA JR. DE BUSINESS INTELLIGENCE','id_nivel'=>5,'id_sede_laboral'=>4,'perfil_infosap'=>'','estado'=>1],            
        ];

        foreach ($list_puesto as $list) {
            Puesto::create([
                'id_direccion' => $list['id_direccion'],
                'id_gerencia' => $list['id_gerencia'],
                'id_departamento' => $list['id_departamento'],
                'id_area' => $list['id_area'],
                'nom_puesto' => $list['nom_puesto'],
                'id_nivel' => $list['id_nivel'],
                'id_sede_laboral' => $list['id_sede_laboral'],
                'perfil_infosap' => $list['perfil_infosap'],
                'estado' => $list['estado'],
            ]);
        }
    }
}